apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks
  template:
    metadata:
      labels:
        app: eks
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
      containers:
        - name: eks
          image: annancs/cloud-docker-kubrnt:latest
          ports:
            - containerPort: 8080
