apiVersion: v1
kind: Service
metadata:
  name: eks-service
  namespace: default
spec:
  selector:
    app: eks
  ports:
    - nodePort: 31479 
      port: 8080
      targetPort: 8080
  type: LoadBalancer
