apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
          image: annancs/cloud-docker-kubrnt:amd64v.3
          name: web
          livenessProbe:
            httpGet: 
              path: /health 
              port: 8080
          readinessProbe:
            httpGet:
              path: /ready 
              port: 8080
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
